### ISSUE TITLE
Your About dialog's URL links to KeePassX instead of this repo

### ISSUE THREAD

**Issue by MightyPork** [suratovvlad/libqdark#5]
https://github.com/suratovvlad/libqdark/blob/master/src/AboutDarkThemePluginDialog.ui#L43

![screenshot_20180430_093428](https://user-images.githubusercontent.com/2041118/39418263-b0592924-4c59-11e8-98c4-3571f379ce43.png)
![screenshot_20180430_093439](https://user-images.githubusercontent.com/2041118/39418268-b868ac5c-4c59-11e8-8226-ce6df94cba16.png)

**Comment by suratovvlad** [comment]
Oh. I'll check it later, thanks

**Comment by suratovvlad** [comment]
Fixed
